# Matrix powers

The goal of this notebook is to show how to compute products of matrices and powers of matrices using Python. First, we import the `numpy` library, which provides tools for such computations:

In [1]:
import numpy as np

Next we define a couple matrices using `numpy`:

In [2]:
A = np.array([[1, 2, 3],
              [4, 3, 6],
              [7, 8, 9]])

B = np.array([[0, 1, 3],
              [2, 5, 2],
              [0, 0, 1]])

In [3]:
print(A)

[[1 2 3]
 [4 3 6]
 [7 8 9]]


In [4]:
print(B)

[[0 1 3]
 [2 5 2]
 [0 0 1]]


## Matrix multiplication

The operator `@` performs matrix multiplication:

In [5]:
A@B

array([[ 4, 11, 10],
       [ 6, 19, 24],
       [16, 47, 46]])

## Matrix powers

To take a power of a matrix we can multiply it by itself some number of times:

In [6]:
# compute the 4th power of A
A@A@A@A

array([[ 7040,  7660, 10248],
       [14078, 15321, 20496],
       [24740, 26914, 36024]])

However, it is simpler and faster to use the `np.linalg.matrix_power` function that it designed to compute a given power of a matrix:

In [7]:
# compute the 4th power of A
np.linalg.matrix_power(A, 4)

array([[ 7040,  7660, 10248],
       [14078, 15321, 20496],
       [24740, 26914, 36024]])

## Sum of entries of a matrix

Here is one more numpy computation that may come handy in Homework 4. If `A` is a numpy matrix then 
`A.sum()` computes the sum of all entries of `A`.

In [8]:
print(A)

[[1 2 3]
 [4 3 6]
 [7 8 9]]


In [9]:
A.sum()

43

In [10]:
A1 = np.array([[0,0,0,1,0,0],
               [1,0,1,0,0,0],
               [0,0,0,1,1,0],
               [0,1,0,0,0,1],
               [0,0,1,1,0,1],
               [1,1,0,0,1,0]])

A1@A1@A1@A1@A1@A1@A1@A1@A1@A1

array([[157, 148, 151, 201, 133, 142],
       [258, 302, 215, 303, 248, 259],
       [404, 414, 399, 520, 341, 409],
       [290, 343, 281, 441, 293, 334],
       [533, 586, 474, 703, 515, 527],
       [419, 473, 421, 561, 367, 475]])

In [11]:
A2 = np.array([[0,0,1,0,0],
               [1,0,0,0,0],
               [0,1,0,0,1],
               [0,0,1,0,1],
               [1,1,0,1,0]])

A2@A2@A2@A2@A2@A2@A2@A2@A2@A2

array([[33, 27, 39, 13, 26],
       [27, 20, 14, 12, 13],
       [53, 65, 46, 26, 52],
       [77, 77, 77, 34, 66],
       [90, 78, 65, 40, 59]])

In [12]:
A = np.array([[0,1,1,1,1],
              [1,0,1,1,0],
              [1,1,1,0,1],
              [1,1,0,1,1],
              [1,0,1,1,1]])

A8 = A@A@A@A@A@A@A@A
print(A8)
print(A8.sum())

[[ 9970  7787  9969  9969 10533]
 [ 7787  6096  7787  7787  8238]
 [ 9969  7787  9970  9969 10533]
 [ 9969  7787  9969  9970 10533]
 [10533  8238 10533 10533 11137]]
233353


In [5]:
A1 = np.array([[0,1,0,1,0,0],
               [0,0,0,1,1,1],
               [0,1,0,0,0,1],
               [1,0,1,0,0,1],
               [0,0,1,1,0,0],
               [0,0,1,1,1,0]])

A1@A1@A1@A1@A1@A1@A1@A1@A1@A1

array([[ 918, 1301, 2394, 2337, 1420, 2362],
       [1187, 1698, 3109, 3066, 1879, 3085],
       [ 905, 1295, 2357, 2299, 1394, 2331],
       [1150, 1614, 3010, 2935, 1784, 2947],
       [ 804, 1118, 2105, 2055, 1252, 2060],
       [1112, 1564, 2915, 2859, 1747, 2866]])